Interim commit

diff --git a/.github/workflows/cpp-linter.yaml b/.github/workflows/cpp-linter.yaml
--- a/.github/workflows/cpp-linter.yaml
+++ b/.github/workflows/cpp-linter.yaml
@@ -21,8 +21,8 @@ jobs:
           tidy-checks: '' # Use .clang-tidy config file
           # only 'update' a single comment in a pull request thread.
           thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
-      - name: Fail fast?!
+      - name: Fail fast
         if: steps.linter.outputs.checks-failed > 0
         run: |
-            echo "Some linter checks failed. ${{ steps.linter.outputs.checks-failed }}"
-        # run: exit 1
+            echo "Some linter checks failed. ${{ steps.linter.outputs.checks-failed }}" |
+            exit 1
